apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "auth-db.fullname" . }}-pvc
  labels:
    app: {{ include "auth-db.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi